---
title: "SEBS_station_map"
output: html_document
date: "2026-02-27"
editor_options: 
  chunk_output_type: console
---
```{r}
#ggplot, data manipulation
library(tidyverse)
#getNOAABathy lines
library(marmap)
#for plotting maps and projections
library(maps)
library(mapdata)
library(mapproj)
library(ggspatial)
```

```{r}
#read in Alaska polygon for mapping
US <- map_data("world2Hires",region="USA")
AK <- subset(US,subregion == "Alaska")
USSR <- map_data("world2Hires",region="USSR")
NBS <- rbind(AK,USSR)
#transforms longitudes (you could also transform the longs in the data file)
NBS$long <- NBS$long-360

#read in bathymetry file.  

#alternative 
bathline <- getNOAA.bathy(-180,-158,50,65)

#read in station coordinate file
stations <- read.csv("SEBS_mapping/data/Appendix2_DY22-08_BASISStationCoordinates.csv")

```


```{r}
stn <- ggplot() +
  #alaska polygon
  geom_polygon(data=NBS,aes(x=long,y=lat,group=group),fill="tan") +
  #bathymetry
  geom_contour (data=bathline,aes(x=x,y=y,z=z),breaks=c(-50),size=c(0.3),colour="seagreen") +
  geom_contour (data=bathline,aes(x=x,y=y,z=z),breaks=c(-20),size=c(0.3),colour="seagreen") +
  geom_contour(data=bathline,aes(x=x,y=y,z=z),breaks=c(-200),size=c(0.3),colour="seagreen") +
  #station coordinates as points
  geom_point(data=stations, aes(x = Londd, y = Latdd, shape = DesignType)) +
  #bathymetry labels
  annotate( geom = "text", x = -165.5, y = 59.5, label = "20m", 
            color = "black", size = 2 )+
  annotate( geom = "text", x = -166, y = 58.2, label = "50m", 
            color = "black", size = 2 )+
  annotate( geom = "text", x = -168.1, y = 56, label = "200m", 
            color = "black", size = 2 ) +
  scale_shape_manual(name = "Station type",values=c(24, 17, 13)) +
  #projection and limits using coord_sf
  coord_sf(crs="EPSG:3476",default_crs=sf::st_crs(4326),xlim=c(-180,-158),ylim=c(54,64)) +
  ##alternatively you can use coord_map.  These both work for projections.  The below line is what i use for the CPUE maps and it generally works better.
  #coord_map(proj="azequidistant",orientation=c(90,180,20),xlim=c(-175,-158),ylim=c(55,60))
  #axis and legend label
  labs(x="Longitude (°W)",y="Latitude (°N)") +
  #lat/lon tick labels
  scale_y_continuous(breaks=c(54,56,58,60,62, 64)) +
  scale_x_continuous(breaks=c(-180, -175,-170,-165,-160)) +
  annotation_scale(text_cex = 1, line_width = 2, style = "ticks", location = "bl") +
  #blank legend background
  #lat/long graticule color and transparency
  theme(panel.background=element_rect(fill="transparent"),
        panel.grid=element_line(color="gray",size=0.5,linetype=1),
        axis.ticks=element_blank(),
        text = element_text(size = 20)) 


ggsave(stn, filename="images/BASIS_stn_map.png",width=12,height=12,units=c("in"),dpi=300)

```

